import React from 'react';

const Sitemap = () => {
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
      <loc>https://creditmitra.in/</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>1.0</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/products</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/responsibleLending</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/contact</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/about</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/ourLendingPartners</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/faq</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/grievanceredressal</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/privacypolicy</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/termsAndConditions</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/blogs</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.6</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/blogs/8-tips-to-improve-your-cibil-score</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.5</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/blogs/improving-your-cibil-score-is-not-rocket-science</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.5</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/emergency-loan</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.9</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/instant-personal-loan-online</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.9</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/medical-loan</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.9</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/personal-loan-for-salaried</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.9</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/travel-loan</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.9</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/marriage-loan</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.9</priority>
    </url>
    <url>
      <loc>https://creditmitra.in/calculator</loc>
      <lastmod>2024-05-20</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.7</priority>
    </url>
  </urlset>`;

  return (
    <div>
      <pre>{sitemap}</pre>
    </div>
  );
};

export default Sitemap;
